// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
    [
        { "name": "PluginCommonBase", "status": true, "description": "Plugin Analysis Common Base", "parameters": {} },
        { "name": "MoviePicture", "status": true, "description": "MovieInScreenPlugin", "parameters": { "MovieVolumeType": "none", "AutoEraseOnEnd": "true", "MovieFolder": "", "WebmExt": "", "Mp4Ext": "" } },
        { "name": "AltMenuScreen", "status": false, "description": "Alternative menu screen layout.", "parameters": {} }
    ];
